from pathlib import Path


def build_self_update_script(
    current_exe: Path,
    update_path: Path,
    backup_path: Path,
    update_log_path: Path,
    script_path: Path,
) -> str:
    lines = [
        "@echo off",
        "setlocal",
        f'set "LOG={update_log_path}"',
        'echo [%date% %time%] Iniciando auto-update do PrintBillingAgent >> "%LOG%"',
        "timeout /t 3 /nobreak > nul",
        'set "STAGE=parar servico"',
        'echo [%date% %time%] Parando servico >> "%LOG%"',
        "sc stop PrintBillingAgent > nul 2>&1",
        "timeout /t 5 /nobreak > nul",
        'set "STAGE=criar backup"',
        'echo [%date% %time%] Criando backup do executavel atual >> "%LOG%"',
        f'copy /Y "{current_exe}" "{backup_path}" > nul',
        "if errorlevel 1 goto rollback",
        'set "STAGE=substituir executavel"',
        'echo [%date% %time%] Aplicando nova versao >> "%LOG%"',
        f'copy /Y "{update_path}" "{current_exe}" > nul',
        "if errorlevel 1 goto rollback",
        'set "STAGE=iniciar servico atualizado"',
        'echo [%date% %time%] Iniciando servico atualizado >> "%LOG%"',
        "sc start PrintBillingAgent > nul 2>&1",
        "if errorlevel 1 goto rollback",
        'echo [%date% %time%] Auto-update concluido com sucesso >> "%LOG%"',
        f'echo [%date% %time%] Backup preservado em "{backup_path}" >> "%LOG%"',
        "goto cleanup",
        ":rollback",
        'echo [%date% %time%] Falha na etapa "%STAGE%"; restaurando backup >> "%LOG%"',
        f'copy /Y "{backup_path}" "{current_exe}" > nul 2>&1',
        'if errorlevel 1 echo [%date% %time%] Falha ao restaurar backup >> "%LOG%"',
        'echo [%date% %time%] Reiniciando servico apos rollback >> "%LOG%"',
        "sc start PrintBillingAgent > nul 2>&1",
        'if errorlevel 1 echo [%date% %time%] Falha ao iniciar servico apos rollback >> "%LOG%"',
        ":cleanup",
        'echo [%date% %time%] Limpando arquivos temporarios >> "%LOG%"',
        f'del "{update_path}" > nul 2>&1',
        f'del "{script_path}" > nul 2>&1',
    ]
    return "\r\n".join(lines)
